name: mighty_fitness
description: A new Flutter project.

publish_to: 'none'

version: 1.3.0+13

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  image: ^4.1.3

  flutter:
    sdk: flutter

  #Basic
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  flutter_vector_icons: ^2.0.0
  lottie: ^3.3.1
  device_preview: ^1.2.0

  flutter_chrome_cast:
    git:
      url: https://github.com/iqonic-design/flutter_google_cast.git
      ref: 1.1.0


  #Network
  http: ^1.3.0
  connectivity_plus:

  #State Management
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0

  flutter_inappwebview: ^6.0.0

  #Storage
  shared_preferences: ^2.5.2

  audioplayers: ^6.4.0


  flutter_staggered_grid_view: ^0.7.0


  #calendar
  table_calendar: ^3.1.2

  syncfusion_flutter_datepicker: ^26.2.13

  circular_countdown_timer:
  device_info_plus:
  animated_background:
  top_snackbar_flutter:

  # Firebase
  firebase_core: ^3.3.0
  firebase_analytics: ^11.2.1
  firebase_crashlytics: ^4.0.4
  firebase_auth: ^5.1.3
  firebase_storage: ^12.1.1
  firebase_messaging: ^15.2.4
  cloud_firestore: ^5.1.0
  file_picker: ^8.1.6
  paginate_firestore:
    git:
      url: https://github.com/waqadArshad/paginate_firestore.git

  #login
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1


  flutter_toggle_tab: 1.4.1

  #one signal
  onesignal_flutter: ^5.2.2

  #notification
  awesome_notifications: ^0.10.1

  #OTP
  pinput: ^5.0.1

  #Video player
  youtube_player_flutter:
  chewie: 1.8.1
  fetch_client: 1.1.1
  video_player: ^2.9.2


  #ads
  google_mobile_ads: ^5.1.0

  #step count
  pedometer: ^4.0.2

  #gpt
  chat_gpt_flutter: ^1.0.16
  chat_gpt_sdk: ^3.1.0


  #Other
  marquee:
  fluttertoast: ^8.2.6
  country_code_picker: ^3.1.0
  infinite_listview: ^1.1.0
  html: ^0.15.4
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  # flutter_html:
  #   git:
  #     url: https://github.com/appmeetmighty/flutter_html.git
  flutter_tts: ^4.0.2
  draggable_bottom_sheet: ^1.0.2
  share_plus: ^10.0.0
  flutter_time_picker_spinner: ^2.0.0
  flutter_bounce: ^1.1.0
  card_swiper: ^3.0.1
  simple_pip_mode: ^0.8.0
  photo_view: ^0.15.0
  tuple: ^2.0.2

  #localizations
  flutter_localizations:
    sdk: flutter

  #chart
  syncfusion_flutter_charts: ^26.2.14
  path_provider: ^2.1.4
  #sizer: ^3.0.2

  crisp_chat: ^2.2.4

  animated_text_kit: ^4.2.3

  stripe_platform_interface: 11.3.0

  #payment
 # razorpay_flutter: ^1.3.7
  razorpay_flutter: ^1.4.0
  flutter_stripe: ^11.0.0
  bambara_flutter: ^0.0.6
  pay_with_paystack: ^1.0.13
  # flutter_paystack:
  #   git:
  #     url: https://github.com/appmeetmighty/flutter_paystack/
  # flutter_braintree: ^4.0.0
  flutter_paytabs_bridge: ^2.6.18

  my_fatoorah: ^3.3.0

  camera: ^0.10.0

dependency_overrides:
  intl: ^0.18.1
  http: ^0.13.5
  flutter_svg: ^1.0.0
  flutter_layout_grid: ^2.0.5
  webview_flutter: ^4.8.0
  cloud_firestore: ^5.1.0
  fading_edge_scrollview:
  flutter_math_fork:
    git:
      url: https://github.com/simpleclub/flutter_math.git
      ref: main
  flutter_html: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1
  #flutter packages pub run build_runner build --delete-conflicting-outputs
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/Flag/
    - assets/sounds/coins.mp3
    - assets/sounds/wrong.mp3
    - assets/sounds/startplay.mp3
    - assets/loading.json
